[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 88
py_version = 311
combine_as_imports = true
force_sort_within_sections = true
known_first_party = ["e_websearch", "core", "api", "tests", "examples"]
default_section = "THIRDPARTY"
skip_gitignore = true
src_paths = ["."]


